import type { Metadata } from "next";
import { Play } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { UiPlayer } from "@/components/ui-player";

const fontSans = Play({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(fontSans.className, "relative overflow-hidden h-[100vh]")}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <div className="absolute left-[45%] bottom-10">
            <UiPlayer /> {/* Add UiPlayer here */}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
